insert into cities (id,region_id,name) values (1,1,'Andijon shaxri');
insert into cities (id,region_id,name) values (2,1,'Andijon tumani');
insert into cities (id,region_id,name) values (3,1,'Asaka tumani');
insert into cities (id,region_id,name) values (4,1,'Shaxrixon tumani');
insert into cities (id,region_id,name) values (5,1,'Bo‘z tumani');
insert into cities (id,region_id,name) values (6,1,'Ulugnor tumani');
insert into cities (id,region_id,name) values (7,1,'Oltinko‘l tumani');
insert into cities (id,region_id,name) values (8,1,'Baliqchi tumani');
insert into cities (id,region_id,name) values (9,1,'Izboskan tumani');
insert into cities (id,region_id,name) values (10,1,'Buloqboshi tumani');
insert into cities (id,region_id,name) values (11,1,'Paxtaobod tumani');
insert into cities (id,region_id,name) values (12,1,'Jalaquduq tumani');
insert into cities (id,region_id,name) values (13,1,'Qo‘rg‘ontepa tumani');
insert into cities (id,region_id,name) values (14,1,'Qorasuv shaxri');
insert into cities (id,region_id,name) values (15,1,'Xonobod shaxri');
insert into cities (id,region_id,name) values (16,1,'Xo‘jaobod tumani');
insert into cities (id,region_id,name) values (17,1,'Marxamat tumani');
insert into cities (id,region_id,name) values (18,2,'Peshku');
insert into cities (id,region_id,name) values (19,2,'Olot');
insert into cities (id,region_id,name) values (20,2,'Romitan');
insert into cities (id,region_id,name) values (21,2,'Shofirkon');
insert into cities (id,region_id,name) values (22,2,'G‘ijduvon');
insert into cities (id,region_id,name) values (23,2,'Qorako‘l');
insert into cities (id,region_id,name) values (24,2,'Kogon shahar');
insert into cities (id,region_id,name) values (25,2,'Kogon tuman');
insert into cities (id,region_id,name) values (26,2,'Buxoro shahar');
insert into cities (id,region_id,name) values (27,2,'Buxoro tuman');
insert into cities (id,region_id,name) values (28,2,'Vobkent');
insert into cities (id,region_id,name) values (29,2,'Jondor');
insert into cities (id,region_id,name) values (30,2,'Qorovulbozor');
insert into cities (id,region_id,name) values (31,3,'Qarshi shahar');
insert into cities (id,region_id,name) values (32,3,'G‘uzor tumani');
insert into cities (id,region_id,name) values (33,3,'Kitob tumani');
insert into cities (id,region_id,name) values (34,3,'Qamashi tumani');
insert into cities (id,region_id,name) values (35,3,'Koson tumani');
insert into cities (id,region_id,name) values (36,3,'Mirishkor tumani');
insert into cities (id,region_id,name) values (37,3,'Muborak tumani');
insert into cities (id,region_id,name) values (38,3,'Kasbi tumani');
insert into cities (id,region_id,name) values (39,3,'Nishon tumani');
insert into cities (id,region_id,name) values (40,3,'Shahrisabz t');
insert into cities (id,region_id,name) values (41,3,'Yakkabog‘ tumani');
insert into cities (id,region_id,name) values (42,3,'Chiroqchi tumani');
insert into cities (id,region_id,name) values (43,3,'Dehqonobod t');
insert into cities (id,region_id,name) values (44,3,'Qarshi tumani');
insert into cities (id,region_id,name) values (45,4,'Nukus tumani');
insert into cities (id,region_id,name) values (46,4,'Nukus shaxri');
insert into cities (id,region_id,name) values (47,4,'Beruniy ');
insert into cities (id,region_id,name) values (48,4,'Muynok');
insert into cities (id,region_id,name) values (49,4,'Ellikqal’a tumani');
insert into cities (id,region_id,name) values (50,4,'Shumanoy');
insert into cities (id,region_id,name) values (51,4,'Xo‘jayli tumani');
insert into cities (id,region_id,name) values (52,4,'Chimboy');
insert into cities (id,region_id,name) values (53,4,'Qonliko‘l');
insert into cities (id,region_id,name) values (54,4,'Kegeyli');
insert into cities (id,region_id,name) values (55,4,'Korauzak');
insert into cities (id,region_id,name) values (56,4,'Taxtakupir');
insert into cities (id,region_id,name) values (57,4,'Turtkul');
insert into cities (id,region_id,name) values (58,4,'Kurgirot');
insert into cities (id,region_id,name) values (59,4,'Amudarya');
insert into cities (id,region_id,name) values (60,5,'Navoiy shahar');
insert into cities (id,region_id,name) values (61,5,'Zarafshon shahar');
insert into cities (id,region_id,name) values (62,5,'Karmana tumani');
insert into cities (id,region_id,name) values (63,5,'Qiziltepa tumani');
insert into cities (id,region_id,name) values (64,5,'Xatirchi tumani');
insert into cities (id,region_id,name) values (65,5,'Navbahor tumani');
insert into cities (id,region_id,name) values (66,5,'Nurota tumani');
insert into cities (id,region_id,name) values (67,5,'Konimex tumani');
insert into cities (id,region_id,name) values (68,5,'Uchquduq tumani');
insert into cities (id,region_id,name) values (69,5,'Tomdi tumani');
insert into cities (id,region_id,name) values (70,6,'Mingbuloq');
insert into cities (id,region_id,name) values (71,6,'Kosonsoy ');
insert into cities (id,region_id,name) values (72,6,'Namangan tumani');
insert into cities (id,region_id,name) values (73,6,'Norin');
insert into cities (id,region_id,name) values (74,6,'Pop');
insert into cities (id,region_id,name) values (75,6,'To‘raqo‘rg‘on');
insert into cities (id,region_id,name) values (76,6,'Uychi');
insert into cities (id,region_id,name) values (77,6,'Uchqo‘rg‘on');
insert into cities (id,region_id,name) values (78,6,'Chortoq');
insert into cities (id,region_id,name) values (79,6,'Chust');
insert into cities (id,region_id,name) values (80,6,'Yangiqo‘rg‘on');
insert into cities (id,region_id,name) values (81,6,'Namangan shahar');
insert into cities (id,region_id,name) values (82,7,'Samarqand shahar ');
insert into cities (id,region_id,name) values (83,7,'Samarqand tumani ');
insert into cities (id,region_id,name) values (84,7,'Bulung‘ur tumani ');
insert into cities (id,region_id,name) values (85,7,'Jomboy tumani ');
insert into cities (id,region_id,name) values (86,7,'Ishtixon tumani ');
insert into cities (id,region_id,name) values (87,7,'Kattaqurg‘on tumani ');
insert into cities (id,region_id,name) values (88,7,'Kattaqurg‘on shahar');
insert into cities (id,region_id,name) values (89,7,'Narpay tumani ');
insert into cities (id,region_id,name) values (90,7,'Nurobod tumani ');
insert into cities (id,region_id,name) values (91,7,'Oqdaryo tumani');
insert into cities (id,region_id,name) values (92,7,'Payariq tumani ');
insert into cities (id,region_id,name) values (93,7,'Pastdarg‘om tumani ');
insert into cities (id,region_id,name) values (94,7,'Paxtachi tumani ');
insert into cities (id,region_id,name) values (95,7,'Tayloq tumani ');
insert into cities (id,region_id,name) values (96,7,'Qo‘shrabot tumani ');
insert into cities (id,region_id,name) values (97,7,'Urgut tumani ');
insert into cities (id,region_id,name) values (98,8,'Guliston sh');
insert into cities (id,region_id,name) values (99,8,'Shirin sh');
insert into cities (id,region_id,name) values (100,8,'Yangiyer sh');
insert into cities (id,region_id,name) values (101,8,'Boyovut');
insert into cities (id,region_id,name) values (102,8,'Oqoltin');
insert into cities (id,region_id,name) values (103,8,'Mirzaobod');
insert into cities (id,region_id,name) values (104,8,'Sardoba');
insert into cities (id,region_id,name) values (105,8,'Sirdaryo');
insert into cities (id,region_id,name) values (106,8,'Sayxunobod');
insert into cities (id,region_id,name) values (107,8,'xovos');
insert into cities (id,region_id,name) values (108,8,'Guliston t');
insert into cities (id,region_id,name) values (109,9,'Marg‘ilon shahar');
insert into cities (id,region_id,name) values (110,9,'Farg‘ona shahar');
insert into cities (id,region_id,name) values (111,9,'Quvasoy shahri');
insert into cities (id,region_id,name) values (112,9,'Qo‘qon shahri');
insert into cities (id,region_id,name) values (113,9,'Bog‘dod tumani');
insert into cities (id,region_id,name) values (114,9,'Beshariq tuman');
insert into cities (id,region_id,name) values (115,9,'Buvayda tumani');
insert into cities (id,region_id,name) values (116,9,'Dang‘ara tumani');
insert into cities (id,region_id,name) values (117,9,'Yozyovon tumani');
insert into cities (id,region_id,name) values (118,9,'Oltiariq tumani');
insert into cities (id,region_id,name) values (119,9,'Qo‘shtepa tumani');
insert into cities (id,region_id,name) values (120,9,'Rishton tumani');
insert into cities (id,region_id,name) values (121,9,'So‘x tumani');
insert into cities (id,region_id,name) values (122,9,'Toshloq tumani');
insert into cities (id,region_id,name) values (123,9,'Uchko‘prik tumani');
insert into cities (id,region_id,name) values (124,9,'Farg‘ona tumani');
insert into cities (id,region_id,name) values (125,9,'Furqat tumani ');
insert into cities (id,region_id,name) values (126,9,'O‘zbekiston tumani');
insert into cities (id,region_id,name) values (127,9,'Quva tumani');
insert into cities (id,region_id,name) values (128,10,'Angren shahar');
insert into cities (id,region_id,name) values (129,10,'Bekobod tumani');
insert into cities (id,region_id,name) values (130,10,'Bekobod shahar');
insert into cities (id,region_id,name) values (131,10,'Bo‘ka tumani');
insert into cities (id,region_id,name) values (132,10,'Bo‘stonliq tumani');
insert into cities (id,region_id,name) values (133,10,'Zangiota tumani');
insert into cities (id,region_id,name) values (134,10,'Ohangaron tumani');
insert into cities (id,region_id,name) values (135,10,'Olmaliq shahar');
insert into cities (id,region_id,name) values (136,10,'Oqqo‘rg‘on tumani');
insert into cities (id,region_id,name) values (137,10,'Parkent tumani');
insert into cities (id,region_id,name) values (138,10,'Piskent tumani');
insert into cities (id,region_id,name) values (139,10,'Yuqorichirchiq tumani');
insert into cities (id,region_id,name) values (140,10,'Chinoz tumani');
insert into cities (id,region_id,name) values (141,10,'Chirchiq shahar');
insert into cities (id,region_id,name) values (142,10,'O‘rtachirchiq tumani');
insert into cities (id,region_id,name) values (143,10,'Quyichirchiq tumani');
insert into cities (id,region_id,name) values (144,10,'Qibray tumani');
insert into cities (id,region_id,name) values (145,10,'Yangiyo‘l tumani');
insert into cities (id,region_id,name) values (146,11,'Bektemir');
insert into cities (id,region_id,name) values (147,11,'Mirzo Ulug‘bek');
insert into cities (id,region_id,name) values (148,11,'Mirobod');
insert into cities (id,region_id,name) values (149,11,'Olmazor');
insert into cities (id,region_id,name) values (150,11,'Sergeli');
insert into cities (id,region_id,name) values (151,11,'Uchtepa');
insert into cities (id,region_id,name) values (152,11,'Chilonzor');
insert into cities (id,region_id,name) values (153,11,'Shayxontohur');
insert into cities (id,region_id,name) values (154,11,'Yunusobod');
insert into cities (id,region_id,name) values (155,11,'Yakkasaroy');
insert into cities (id,region_id,name) values (156,11,'Yashnobod');
insert into cities (id,region_id,name) values (157,12,'Bog‘ot t.');
insert into cities (id,region_id,name) values (158,12,'Gurlan t.');
insert into cities (id,region_id,name) values (159,12,'Qo‘shko‘pir t.');
insert into cities (id,region_id,name) values (160,12,'Xazorasp t.');
insert into cities (id,region_id,name) values (161,12,'Xiva t.');
insert into cities (id,region_id,name) values (162,12,'Honqa t.');
insert into cities (id,region_id,name) values (163,12,'Yangiariq t.');
insert into cities (id,region_id,name) values (164,12,'Yangibozor t.');
insert into cities (id,region_id,name) values (165,12,'Shovot t.');
insert into cities (id,region_id,name) values (166,12,'Urganch t.');
insert into cities (id,region_id,name) values (167,12,'Urganch sh.');
insert into cities (id,region_id,name) values (168,13,'Arnasoy tumani');
insert into cities (id,region_id,name) values (169,13,'Baxmal tumani');
insert into cities (id,region_id,name) values (170,13,'Doʻstlik tumani');
insert into cities (id,region_id,name) values (171,13,'Forish tumani');
insert into cities (id,region_id,name) values (172,13,'Gʻallaorol tumani');
insert into cities (id,region_id,name) values (173,13,'Sharof Rashidov tumani');
insert into cities (id,region_id,name) values (174,13,'Mirzachoʻl tumani');
insert into cities (id,region_id,name) values (175,13,'Paxtakor tumani');
insert into cities (id,region_id,name) values (176,13,'Yangiobod tumani');
insert into cities (id,region_id,name) values (177,13,'Zomin tumani');
insert into cities (id,region_id,name) values (178,13,'Zafarobod tumani');
insert into cities (id,region_id,name) values (179,13,'Zarbdor tumani');
